---
title: "crime_municipalities"
author: "Nikita"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries, include=FALSE}
# Library 
library(raster)
library(rgeos)
library(sf)
library(tidyverse)
library(htmltools)
library(googlesheets4)
library(mapview)
library(leaflet)
library(shiny)
```


```{r load-municipalities-spatial-data, echo = FALSE}

# Load the spatial data, project to UTM
mun_sp<- getData('GADM', country = 'DK', level = 2)
mun_sf <- st_as_sf(mun_sp)
mun <- st_transform(mun_sf, crs = 25832)
st_crs(mun)

# Plot so as to check correct location and complete coverage
plot(mun$geometry)

# Check the names
mun$NAME_2

# Straighten the names (return here after Task 2)
mun$NAME_2[31] <- "Aarhus"
mun$NAME_2[21] <- "Høje-Taastrup"
mun$NAME_2[60] <- "Vesthimmerlands"


```


```{r load vold }
# read in data from csv
voldsforbrydelser <- read_csv2("data/forbrydelse_alle_numbers.csv")
befolkningstal <- read_csv2("data/befolkningstal_år_kolon_numbers.csv")
# delete row 1 and 3 and column 1
#voldsforbrydelser <- voldsforbrydelser[-c(1,3), -1]
#rename colums with names of the first row
colnames(voldsforbrydelser) <- voldsforbrydelser[1, ]
# delete row with rownames
voldsforbrydelser <- voldsforbrydelser[-1,]
# drop NA-rows
#voldsforbrydelser <- voldsforbrydelser[complete.cases(voldsforbrydelser), ]
#drop 'ukendt kommune' row
voldsforbrydelser <- voldsforbrydelser[-100,]
# pasting 'Y' before columnname
colnames(voldsforbrydelser) <- paste0("Y", colnames(voldsforbrydelser))
# rename the first column
#colnames(voldsforbrydelser)[1] <- "municipalities"

# assign numbers as numbers
voldsforbrydelser[,2:6] <- sapply(voldsforbrydelser[ ,2:6], as.numeric)
# getting sum of rows
voldsforbrydelser$crime_sum <- rowSums(voldsforbrydelser[,2:6])


# edit befolkningstl csv
befolkningstal <- befolkningstal[-c(1),]
#rename colums with names of the first row
colnames(befolkningstal) <- befolkningstal[1, ]
# delete row with rownames
befolkningstal <- befolkningstal[-1,]
# drop NA-rows
befolkningstal <- befolkningstal[complete.cases(befolkningstal), ]
#drop 'ukendt kommune' row
befolkningstal <- befolkningstal[-100,]
# pasting 'Y' before columnname
colnames(befolkningstal) <- paste0("Y", colnames(befolkningstal))
# rename the first column
colnames(befolkningstal)[1] <- "municipalities"

# assign numbers as numbers
befolkningstal[,2:6] <- sapply(befolkningstal[ ,2:6], as.numeric)
# getting sum of rows
befolkningstal$crime_sum <- rowSums(befolkningstal[,2:6])


crime_rate <- data.frame(Municipality = befolkningstal$municipalities)   # Create a new dataset with the Municipality column from the population dataset

years <- colnames(befolkningstal)[-1]   # Get the years from the population dataset columns

# Loop through each year and calculate the crime rate per 1000 population
for (year in years) {
  pop_col <- befolkningstal[, year]   # Get the population column for the current year
  crime_col <- voldsforbrydelser[, year]   # Get the crime column for the current year
  
  crime_rate[, year] <- (crime_col / pop_col) * 1000   # Calculate the crime rate per 1000 population for the current year
}


# Add columns for the change in crime rate per year
crime_data <- crime_rate %>%
  mutate(change_2019 = Y2019 - Y2018,
         change_2020 = Y2020 - Y2019,
         change_2021 = Y2021 - Y2020,
         change_2022 = Y2022 - Y2021)







```

```{r}

df <- mun %>% 
  select(NAME_2) %>% 
  merge(crime_data, by.x = "NAME_2",by.y ="Municipality")

```

```{r}
data

```

```{r}
percentage_cols <- df[,2:21] / df$crime_sum*100
df[,2:21] <- percentage_cols
```



```{r}

library(shiny)
library(tmap)

df %>% 
  tm_shape() + 
  tm_polygons("Y2018K1",
              title= "Percentage of Votes \nin 2015") +
  tm_text(text = "NAME_2", size = "AREA", root = 100)





```

```{r min koffein induced shitstorm af en leaflet map}
# Load required libraries

library(mapview)
library(shiny)

library(tmap)

# Create a shiny application

  ui = fluidPage(
    titlePanel("Danish Municipality Crime"),
    
      # Create a slider input for selecting the column
    sliderInput("columnSelect", "Select Column:",
              min = 8, max = 11, value = 8, width = "50%"),

    
    # Create a leaflet map output
    tmapOutput("map",height = "1000px")
  )
  
  server= function(input, output, session) {

    
    # Render the map
    output$map <- renderTmap({
          # Get the selected column based on the slider input
      selectedColumn <- colnames(df)[input$columnSelect]
      # Create a mapview object with the selected column
      my_map <- df %>% 
                  tm_shape() + 
                    tm_polygons(selectedColumn,
                                title = paste("Crime per 1000 inhabitants:", selectedColumn),
                                style = "cont",
                                palette = "-RdBu",
                                legend.hist = TRUE) +
                    tm_fill(col = selectedColumn,
                            style = "cont",
                            palette =c("blue", "red"),
                            breaks = c(-Inf, 0, Inf),
                            title = "Percentage of Votes \nin 2015",
                            labels = c("Negative", "Positive"),
                            legend.hist = TRUE) +
                  tm_text(text = "NAME_2") +
                  tm_view(set.view = 8)  # Set the initial zoom level here
 


      

    })
  }


shinyApp(ui, server)







```
```{r min koffein induced shitstorm af en leaflet map}
library(leaflet)
library(shiny)
library(sf)


# Convert dataframe to sf object
sf_data <- st_as_sf(df)

# Transform the coordinate system to WGS84 (latitude and longitude)
sf_data <- st_transform(sf_data, crs = st_crs(4326))

# Create a leaflet map with initial settings
map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron")

# Define the color palette for the polygons
palette <- colorNumeric(palette = "Blues", domain = sf_data$Y2018K1)

# Add the polygons to the map
map <- map %>%
  addPolygons(
    data = sf_data,
    fillColor = ~palette(Y2018K1),
    fillOpacity = 0.8,
    color = "black",
    weight = 1,
    popup = ~paste("Municipality:", NAME_2, "<br>Crimes:", Y2018K1)
  )

# Create a shiny application
shinyApp(
  ui = fluidPage(
    leafletOutput("map"),
    sliderInput(
      "year",
      "Year",
      min = 2018, max = 2022, value = 2018, step = 1
    )
  ),
  server = function(input, output, session) {
    # Update the color palette and fill color based on the selected year
    observeEvent(input$year, {
      selectedYear <- paste0("Y", input$year, "K1")
      palette <- colorNumeric(palette = "Blues", domain = sf_data[[selectedYear]])

      mapProxy <- leafletProxy("map", data = sf_data)
      mapProxy %>%
        clearShapes() %>%
        addPolygons(
          fillColor = ~palette(.data[[selectedYear]]),
          fillOpacity = 0.8,
          color = "black",
          weight = 1,
          popup = ~paste("Municipality:", NAME_2, "<br>Crimes:", .data[[selectedYear]])
        )
    })
  }
)



```

